version: "3.9"

services:

  # -----------------------------
  # ZOOKEEPER
  # -----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: matchx-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -----------------------------
  # KAFKA
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: matchx-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # -----------------------------
  # MATCHX DB (for auth-service)
  # -----------------------------
  postgres:
    image: postgres:16
    container_name: matchx-postgres
    environment:
      POSTGRES_DB: matchxdb
      POSTGRES_USER: matchx
      POSTGRES_PASSWORD: matchxpass
    ports:
      - "5432:5432"
    volumes:
      - matchx_postgres_data:/var/lib/postgresql/data

  # -----------------------------
  # TRADE DB (for trade-persistence-service)
  # -----------------------------
  trade-db:
    image: postgres:16
    container_name: matchx-trade-db
    environment:
      POSTGRES_DB: tradedb
      POSTGRES_USER: tradeuser
      POSTGRES_PASSWORD: tradepass
    ports:
      - "5433:5433"
    volumes:
      - matchx_trade_data:/var/lib/postgresql/data

volumes:
  matchx_postgres_data:
  matchx_trade_data:
